#!/usr/bin/env python3
"""Fetch the Pyquist README and stage it for inclusion in Overview.md.

The Pyquist Overview page is a **verbatim** mirror of the live README on
the upstream repo (gclef-cmu/pyquist), so this script keeps every section
including the `# pyquist` title and the `## Installation` block — the
Overview page is the only intro/install page in the section.

The script:

  1. Downloads the current README from `main`.
  2. Rewrites relative links (e.g. `examples/HelloPyquist.ipynb`) to
     absolute GitHub URLs so they resolve from the book site.
  3. Writes the result to `content/pyquist/_pyquist_readme.md`.

If the network is unavailable, the previous copy on disk is kept. If
neither works, the script exits non-zero so the build surfaces the
failure rather than deploying a half-rendered page.
"""

from __future__ import annotations

import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

REPO = "gclef-cmu/pyquist"
BRANCH = "main"
SOURCE_URL = f"https://raw.githubusercontent.com/{REPO}/{BRANCH}/README.md"
REPO_BLOB_URL = f"https://github.com/{REPO}/blob/{BRANCH}/"

OUT = Path(__file__).resolve().parent.parent / "content" / "pyquist" / "_pyquist_readme.md"

# Header autodoc adds so editors don't confuse this file for hand-authored prose.
HEADER = (
    "<!-- Auto-generated by tools/fetch_pyquist_readme.py. Do not edit by hand. -->\n"
    f"<!-- Source: {SOURCE_URL} -->\n\n"
)


def fetch() -> str:
    req = urllib.request.Request(SOURCE_URL, headers={"User-Agent": "icmbook-build"})
    with urllib.request.urlopen(req, timeout=15) as resp:
        return resp.read().decode("utf-8")


def absolutize_links(text: str) -> str:
    # Markdown links like `[text](relative/path)` — leave anchors, full URLs,
    # and mailtos alone; rewrite anything else as an absolute GitHub blob URL.
    def repl(match: "re.Match[str]") -> str:
        label, target = match.group(1), match.group(2)
        if target.startswith(("http://", "https://", "#", "mailto:")):
            return match.group(0)
        return f"[{label}]({REPO_BLOB_URL}{target.lstrip('./')})"

    return re.sub(r"\[([^\]]+)\]\(([^)]+)\)", repl, text)


def process(raw: str) -> str:
    text = absolutize_links(raw)
    text = text.strip() + "\n"
    return HEADER + text


def main() -> int:
    try:
        raw = fetch()
    except (urllib.error.URLError, TimeoutError) as exc:
        if OUT.exists():
            print(
                f"warning: could not fetch {SOURCE_URL} ({exc}); "
                f"keeping existing {OUT.name}",
                file=sys.stderr,
            )
            return 0
        print(f"error: could not fetch {SOURCE_URL} ({exc}) and no cached "
              f"copy at {OUT}", file=sys.stderr)
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(process(raw), encoding="utf-8")
    print(f"wrote {OUT.relative_to(Path.cwd()) if OUT.is_relative_to(Path.cwd()) else OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
