#!/usr/bin/env python3
"""Split each icm-text/{n}-{slug}/index.md into per-section files under content/ch{nn}/.

Treats the `icm-text/` git submodule (the pinned ground-truth prose repo) as
the source of truth. For each chapter folder:
  - Parses the chapter number from the folder-name prefix (e.g. "2-foo" -> 2).
  - Strips YAML frontmatter and pulls the chapter title from the first `# ` heading.
  - Splits the body on `## ` headings, respecting fenced code blocks so that
    `#`-comments inside ```python``` blocks aren't mistaken for headings.
  - Writes content/ch{nn}/index.md containing `# {n}. {title}` plus the intro
    paragraphs that appeared before the first `## ` section.
  - Writes content/ch{nn}/{ii}.md for each section, demoting every heading one
    level (## -> #, ### -> ##, ...) and prefixing the leading heading with
    `{chapter}.{section_index}`.
  - Copies the chapter's assets/, code/, and figures/ subdirs across so relative
    `./assets/...` links in the source still resolve in the generated tree.
  - Regenerates the chapter parts block of _toc.yml in place.

It then mirrors the icm-f26/ course-website submodule into content/course/. The
course pages are copied verbatim (preserving the directory layout, so a folder
like projects/ or resources/ becomes a nested section with its index.md as the
parent), and the "Course Information" part of _toc.yml is regenerated to list
them in COURSE_ORDER.

Finally, mirrors the ground-truth bibliography icm-text/refs.bib into
content/references.bib (the file _config.yml's `bibtex_bibfiles` points at), so
citations resolve against the same entries the professor maintains upstream.

Both the icm-text and icm-f26 sources are authored directly in MyST, so this
tool performs no syntax translation — it only restructures (split, demote
headings, copy, TOC).

Run via `make split`. WARNING: this wipes content/ch*/ and regenerates it from
icm-text/, dropping any local styling overrides — review `git diff content/`
afterward. The generated content/ch*/ directories are tracked in git and
regenerated by `make split`.
"""
from __future__ import annotations

import ast
import re
import shutil
import sys
from pathlib import Path

import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "icm-text"  # ground-truth prose, pinned git submodule
CONTENT = REPO / "content"
TOC = REPO / "_toc.yml"
REFS_SRC = SOURCE / "refs.bib"  # ground-truth bibliography
REFS_DEST = CONTENT / "references.bib"  # what _config.yml's bibtex_bibfiles points at

COURSE_SOURCE = REPO / "icm-f26"  # ground-truth course website, pinned git submodule
COURSE_DEST = CONTENT / "course"
# The repo's README is a placeholder for contributors, not a course page.
COURSE_SKIP_FILES = {"README.md"}
COURSE_CAPTION = "- caption: Course Information"
# Preferred sidebar order for the course pages/sections (matches the course
# website nav). Entries are file stems or subdirectory names; anything not
# listed sorts naturally after these.
COURSE_ORDER = ("home", "about", "schedule", "projects", "resources", "showcase")

CHAPTER_FOLDER_RE = re.compile(r"^(\d+)-(.+)$")
FRONTMATTER_RE = re.compile(r"\A---\n.*?\n---\n", re.DOTALL)
FENCE_RE = re.compile(r"^\s*(`{3,}|~{3,})")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")

# `:::{interactive}[./code/foo.py]` — a section that contains this directive is
# emitted as a notebook instead of Markdown (see build_interactive_notebook).
# The opening fence is 3+ colons; the path follows on the same line, in
# [brackets] (the authored form) or bare.
INTERACTIVE_OPEN_RE = re.compile(r"^(:{3,})\{interactive\}[ \t]*(.*?)[ \t]*$")


def parse_interactive_arg(arg: str) -> str:
    """Pull the script path out of an `{interactive}` argument.

    Accepts ``[./code/foo.py]`` (the authored bracket form) or a bare path.
    Kept in lockstep with ``_ext/icm_interactive.py``'s copy.
    """
    arg = arg.strip()
    if arg.startswith("[") and arg.endswith("]"):
        arg = arg[1:-1].strip()
    return arg


def interactive_directives(text: str):
    """All `{interactive}` directives in section text, in document order.

    Returns a list of ``(open_idx, close_idx, path)`` line-index triples into
    ``text.splitlines(keepends=True)`` (empty when there are none). A directive
    carries no body, so its closing fence is the next line equal to the opening
    colon run. A section may inline more than one script.
    """
    lines = text.splitlines(keepends=True)
    out: list[tuple[int, int, str]] = []
    i, n = 0, len(lines)
    while i < n:
        m = INTERACTIVE_OPEN_RE.match(lines[i])
        if not m:
            i += 1
            continue
        colons = m.group(1)
        path = parse_interactive_arg(m.group(2))
        close = i
        for j in range(i + 1, n):
            if lines[j].strip() == colons:
                close = j
                break
        out.append((i, close, path))
        i = close + 1
    return out


def _is_def(node) -> bool:
    return isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))


def _is_docstring(node) -> bool:
    return (
        isinstance(node, ast.Expr)
        and isinstance(node.value, ast.Constant)
        and isinstance(node.value.value, str)
    )


# Top-level statements that read as "dependencies and globals" rather than code
# that does something — used to find the setup/execution boundary in a script
# that has no top-level functions to split on.
_SETUP_STMT = (ast.Import, ast.ImportFrom, ast.Assign, ast.AnnAssign)


def decouple_script(code: str) -> list[tuple[str, str]]:
    """Split a script's source into ``(kind, source)`` chunks, one per cell.

    ``kind`` is ``"setup"`` (imports + module globals — the dependency
    boilerplate), ``"func"`` (a single top-level function/class), or ``"exec"``
    (top-level code that actually runs things). The split only *inserts* cell
    boundaries — statements are never reordered, and leading comments/blank lines
    stay attached to the chunk they precede — so running the chunks top to bottom
    reproduces the original script exactly.

    - A script with top-level functions splits on them: everything before the
      first ``def``/``class`` is ``setup``, each definition is its own ``func``
      chunk, and the remaining top-level statements are ``exec``.
    - A function-less script splits its leading imports/docstring/assignments
      (``setup``) from the first statement that actually does something (``exec``).

    Falls back to a single ``exec`` chunk if the source does not parse.
    """
    try:
        body = ast.parse(code).body
    except SyntaxError:
        return [("exec", code.strip("\n"))]
    if not body:
        return [("exec", code.strip("\n"))]

    lines = code.splitlines(keepends=True)
    groups: list[tuple[str, int]] = []  # (kind, index of the group's last stmt)

    if any(_is_def(n) for n in body):
        seen_def = False
        run_open = False  # are we accumulating a run of non-def statements?
        for i, node in enumerate(body):
            if _is_def(node):
                if run_open:
                    groups.append(("exec" if seen_def else "setup", i - 1))
                    run_open = False
                groups.append(("func", i))
                seen_def = True
            elif not run_open:
                run_open = True
        if run_open:
            groups.append(("exec" if seen_def else "setup", len(body) - 1))
    else:
        cut = 0
        for i, node in enumerate(body):
            if isinstance(node, _SETUP_STMT) or (i == 0 and _is_docstring(node)):
                cut = i + 1
            else:
                break
        if cut:
            groups.append(("setup", cut - 1))
        if cut < len(body):
            groups.append(("exec", len(body) - 1))

    out: list[tuple[str, str]] = []
    prev = 0  # source lines already consumed
    for gi, (kind, last_idx) in enumerate(groups):
        end_line = len(lines) if gi == len(groups) - 1 else body[last_idx].end_lineno
        chunk = "".join(lines[prev:end_line]).strip("\n")
        prev = end_line
        if chunk.strip():
            out.append((kind, chunk))
    return out or [("exec", code.strip("\n"))]


def build_interactive_notebook(
    section_md: str, chapter_folder: Path, chapter_num: int, sec_index: int
):
    """Turn a section that inlines scripts into a notebook.

    The section text (already heading-demoted and numbered, exactly the string a
    non-interactive section writes to ``NN.md``) is segmented at each
    ``{interactive}`` directive into Markdown prose and code cells:

      - Markdown cells hold the prose around the directives (the section heading,
        explanation, lead-ins). Empty segments are dropped.
      - each directive's script is **decoupled** (see ``decouple_script``) into
        several executable code cells — imports + globals, one cell per function,
        then the top-level execution — so readers can run and tweak each piece on
        its own. The imports/globals ``setup`` cell is tagged ``hide-input``
        (collapsed — it is boilerplate), the function and execution cells stay
        visible. Every code cell is ``skip-execution``: the scripts write files
        via ``__file__`` and are meant to be run by the reader in the browser
        (_static/live-cells.js defines ``__file__`` and the writes go to a scratch
        FS), not at build time.

    Cell ids are derived from the chapter/section/ordinal so the output is
    byte-for-byte deterministic, which ``tools/merge_chapters.py`` relies on for
    its ``split(merge(content)) == content`` round-trip check. Each script's path
    is stashed in every one of its code cells' metadata; merge collapses the run
    of same-path cells back into one directive.
    """
    lines = section_md.splitlines(keepends=True)
    base = f"ch{chapter_num:02d}s{sec_index:02d}"
    cells: list = []
    k = 0  # running cell ordinal, for deterministic ids

    def add_markdown(seg_lines: list[str]) -> None:
        nonlocal k
        text = "".join(seg_lines).strip("\n")
        if not text:
            return
        cell = new_markdown_cell(text)
        cell["id"] = f"{base}m{k}"
        cell["metadata"] = {}
        cells.append(cell)
        k += 1

    cursor = 0
    for open_idx, close_idx, rel in interactive_directives(section_md):
        add_markdown(lines[cursor:open_idx])
        code = (chapter_folder / rel).read_text()
        for kind, chunk in decouple_script(code):
            cc = new_code_cell(chunk)
            cc["id"] = f"{base}c{k}"
            tags = ["hide-input", "skip-execution"] if kind == "setup" else ["skip-execution"]
            cc["metadata"] = {"tags": tags, "interactive": {"path": rel}}
            cells.append(cc)
            k += 1
        cursor = close_idx + 1
    add_markdown(lines[cursor:])

    nb = new_notebook()
    nb["cells"] = cells
    nb["metadata"] = {
        "kernelspec": {
            "display_name": "Python 3 (ipykernel)",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python"},
    }
    nb["nbformat"] = 4
    nb["nbformat_minor"] = 5
    return nb


def split_body(body: str):
    """Walk the body, splitting on `## ` headings outside fenced code blocks.

    Returns (intro_block_lines, [(section_title, section_content_lines), ...]).
    The intro block still contains the chapter `# ` heading; callers handle it.
    """
    lines = body.splitlines(keepends=True)
    intro_lines: list[str] = []
    sections: list[tuple[str, list[str]]] = []
    cur_title: str | None = None
    cur_lines: list[str] = []
    fence: str | None = None

    def flush():
        nonlocal cur_title, cur_lines
        if cur_title is None:
            intro_lines.extend(cur_lines)
        else:
            sections.append((cur_title, cur_lines))
        cur_title = None
        cur_lines = []

    for line in lines:
        if fence is None:
            fm = FENCE_RE.match(line)
            if fm:
                fence = fm.group(1)
                cur_lines.append(line)
                continue
            hm = HEADING_RE.match(line)
            if hm and len(hm.group(1)) == 2:
                flush()
                cur_title = hm.group(2).strip()
                continue
            cur_lines.append(line)
        else:
            cur_lines.append(line)
            stripped = line.strip()
            # Close on a line that is only fence chars of the same kind, length >= opener.
            if (
                stripped
                and set(stripped) == {fence[0]}
                and len(stripped) >= len(fence)
            ):
                fence = None

    flush()
    return intro_lines, sections


def demote_headings(lines: list[str]) -> list[str]:
    """Demote markdown headings by one level (## -> #, ### -> ##, ...).

    Lines inside fenced code blocks are left untouched.
    """
    out: list[str] = []
    fence: str | None = None
    for line in lines:
        if fence is None:
            fm = FENCE_RE.match(line)
            if fm:
                fence = fm.group(1)
                out.append(line)
                continue
            hm = HEADING_RE.match(line)
            if hm and 2 <= len(hm.group(1)) <= 6:
                out.append(f"{hm.group(1)[1:]} {hm.group(2)}\n")
                continue
            out.append(line)
        else:
            out.append(line)
            stripped = line.strip()
            if (
                stripped
                and set(stripped) == {fence[0]}
                and len(stripped) >= len(fence)
            ):
                fence = None
    return out


def split_chapter(folder: Path) -> dict | None:
    m = CHAPTER_FOLDER_RE.match(folder.name)
    if not m:
        return None
    chapter_num = int(m.group(1))
    src = folder / "index.md"
    if not src.exists():
        print(f"  skip {folder.name}: no index.md", file=sys.stderr)
        return None

    raw = src.read_text()
    body = FRONTMATTER_RE.sub("", raw, count=1)
    intro_lines, sections = split_body(body)

    # Pull the chapter title from the first `# ` in the intro block.
    chapter_title = ""
    intro_after_title: list[str] = []
    seen_title = False
    for line in intro_lines:
        if not seen_title:
            hm = HEADING_RE.match(line)
            if hm and len(hm.group(1)) == 1:
                chapter_title = hm.group(2).strip()
                seen_title = True
                continue
            if line.strip() == "":
                continue
            # Anything else before the title is unexpected; drop it.
            continue
        intro_after_title.append(line)
    intro_text = "".join(intro_after_title).strip("\n")

    out_dir = CONTENT / f"ch{chapter_num:02d}"
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    index_md = f"# {chapter_num}. {chapter_title}\n"
    if intro_text:
        index_md += f"\n{intro_text}\n"
    (out_dir / "index.md").write_text(index_md)

    section_refs: list[str] = []
    for i, (title, content_lines) in enumerate(sections):
        body_text = "".join(demote_headings(content_lines)).strip("\n")
        section_md = f"# {chapter_num}.{i} {title}\n"
        if body_text:
            section_md += f"\n{body_text}\n"
        # A section that inlines a script with `{interactive}` is written as a
        # live notebook; every other section stays Markdown (rendered exactly as
        # before). The TOC entry is extensionless either way, so no _toc.yml
        # change is needed — Jupyter Book resolves NN.ipynb or NN.md.
        if interactive_directives(section_md):
            nb = build_interactive_notebook(section_md, folder, chapter_num, i)
            (out_dir / f"{i:02d}.ipynb").write_text(nbformat.writes(nb) + "\n")
        else:
            (out_dir / f"{i:02d}.md").write_text(section_md)
        section_refs.append(f"content/ch{chapter_num:02d}/{i:02d}")

    for sub in ("assets", "code", "figures"):
        src_sub = folder / sub
        if src_sub.exists():
            shutil.copytree(src_sub, out_dir / sub)

    return {
        "chapter_num": chapter_num,
        "index": f"content/ch{chapter_num:02d}/index",
        "sections": section_refs,
        "slug": folder.name,
        "title": chapter_title,
        "section_count": len(sections),
    }


def regenerate_toc(results: list[dict]) -> None:
    """Rewrite the chapter file-entries (content/ch*/) of _toc.yml in place.

    The chapters live inside the "Textbook" part's `chapters:` list, between the
    template entries above and the reference entry below. This replaces only the
    contiguous run of `- file: content/chNN/index` entries (with their nested
    `sections:`), preserving the surrounding scaffold — the part captions, the
    template entries, and the reference subtree — which is hand-maintained here.
    The run is bounded by the first sibling `- file:` that is not a chapter (e.g.
    content/reference/index) or by a dedent to the enclosing part.
    """
    text = TOC.read_text()
    lines = text.splitlines()

    def indent(line: str) -> int:
        return len(line) - len(line.lstrip())

    starts = [
        i for i, l in enumerate(lines)
        if l.lstrip().startswith("- file: content/ch") and l.rstrip().endswith("/index")
    ]
    if not starts:
        sys.exit("could not locate chapter entries (content/ch*/index) in _toc.yml")
    start = starts[0]
    base = indent(lines[start])

    end = len(lines)
    for j in range(start + 1, len(lines)):
        l = lines[j]
        if not l.strip():
            continue  # blank lines inside the run are dropped
        ind = indent(l)
        is_sibling_file = ind == base and l.lstrip().startswith("- file:")
        if ind < base or (is_sibling_file and not l.lstrip().startswith("- file: content/ch")):
            end = j
            break

    pad = " " * base
    new_block: list[str] = []
    for r in sorted(results, key=lambda r: r["chapter_num"]):
        new_block.append(f"{pad}- file: {r['index']}")
        if r["sections"]:
            new_block.append(f"{pad}  sections:")
            for s in r["sections"]:
                new_block.append(f"{pad}    - file: {s}")

    new_lines = lines[:start] + new_block + lines[end:]
    TOC.write_text("\n".join(new_lines) + "\n")


def natural_key(name: str):
    """Sort key so 1.md, 2.md, ... order numerically and names order lexically."""
    stem = Path(name).stem
    return (0, int(stem), "") if stem.isdigit() else (1, 0, stem.lower())


def _toc_ref(path: Path) -> str:
    """content/course/projects/1.md -> 'content/course/projects/1' (TOC file ref)."""
    return "content/" + path.relative_to(CONTENT).with_suffix("").as_posix()


def course_order_key(path: Path):
    """Sort course pages/subdirs by COURSE_ORDER, then naturally for the rest."""
    rank = COURSE_ORDER.index(path.stem) if path.stem in COURSE_ORDER else len(COURSE_ORDER)
    return (rank, natural_key(path.name))


def regenerate_course_toc() -> None:
    """Replace the "Course Information" part of _toc.yml from content/course/.

    Emits a single captioned jb-book part (a caption attaches to exactly one
    `chapters:` list). Top-level pages and subdirectories are interleaved in
    COURSE_ORDER (so e.g. projects/ sits between schedule and resources): a page
    becomes a flat `file:` entry; a subdirectory's index.md becomes a `file:`
    with its remaining pages nested under `sections:` (a subdir without an
    index.md is listed flat). The part spans from the Course Information caption
    to the next `- caption:`; other parts are untouched.
    """
    entries = sorted(
        (p for p in COURSE_DEST.iterdir() if p.is_dir() or p.suffix == ".md"),
        key=course_order_key,
    )

    body = ["  - caption: Course Information", "    chapters:"]
    for p in entries:
        if not p.is_dir():
            body.append(f"      - file: {_toc_ref(p)}")
            continue
        mds = sorted(p.glob("*.md"), key=lambda q: natural_key(q.name))
        index = next((q for q in mds if q.stem == "index"), None)
        sections = [q for q in mds if q.stem != "index"]
        if index is not None:
            body.append(f"      - file: {_toc_ref(index)}")
            if sections:
                body.append("        sections:")
                body += [f"          - file: {_toc_ref(s)}" for s in sections]
        else:
            body += [f"      - file: {_toc_ref(s)}" for s in sections]

    lines = TOC.read_text().splitlines()
    try:
        cap_idx = next(i for i, l in enumerate(lines) if l.strip() == COURSE_CAPTION)
    except StopIteration:
        sys.exit(f'could not locate "{COURSE_CAPTION}" in _toc.yml')
    end = next(
        (j for j in range(cap_idx + 1, len(lines))
         if lines[j].lstrip().startswith("- caption:")),
        len(lines),
    )
    new_lines = lines[:cap_idx] + body + lines[end:]
    TOC.write_text("\n".join(new_lines) + "\n")


def mirror_course() -> None:
    """Mirror the icm-f26/ course-website submodule verbatim into content/course/.

    icm-f26 authors course pages in the same MyST flavour as the textbook, so —
    unlike the chapters — nothing is split or demoted: every file is copied with
    its directory layout preserved, skipping the README placeholder and any
    dotfiles/dirs (e.g. .git). Wipes content/course/ first, then regenerates the
    Course Information part of _toc.yml.
    """
    if not COURSE_SOURCE.exists() or not any(COURSE_SOURCE.iterdir()):
        print(
            f"  skip course: no {COURSE_SOURCE.relative_to(REPO)}/ "
            "(run: git submodule update --init icm-f26)",
            file=sys.stderr,
        )
        return
    if COURSE_DEST.exists():
        shutil.rmtree(COURSE_DEST)
    COURSE_DEST.mkdir(parents=True)

    copied = 0
    for src in sorted(COURSE_SOURCE.rglob("*")):
        rel = src.relative_to(COURSE_SOURCE)
        if any(part.startswith(".") for part in rel.parts):
            continue  # skip .git and any other dotfiles/dirs
        if src.is_dir() or rel.name in COURSE_SKIP_FILES:
            continue
        dest = COURSE_DEST / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)
        copied += 1

    print(f"  course  {copied} file(s)  <- icm-f26/")
    regenerate_course_toc()
    print(f"  updated {TOC.relative_to(REPO)} (Course Information)")


def sync_references() -> None:
    """Mirror icm-text/refs.bib into content/references.bib.

    The book renders its bibliography from content/references.bib (wired in
    _config.yml via `bibtex_bibfiles`), but the professor maintains the
    ground-truth entries in icm-text/refs.bib. Treat refs.bib the same way we
    treat the chapter prose: copy it verbatim so content/references.bib is a
    generated artifact, not a hand-edited file. A leading @comment marks it as
    generated; bibtex ignores @comment entries.
    """
    if not REFS_SRC.exists():
        print(f"  skip references.bib: no {REFS_SRC.relative_to(REPO)}", file=sys.stderr)
        return
    header = (
        "@comment{\n"
        "  GENERATED FILE -- do not edit by hand.\n"
        "  Synced from icm-text/refs.bib by tools/split_chapters.py (`make split`).\n"
        "  Edit the bibliography in the icm-text submodule instead.\n"
        "}\n\n"
    )
    REFS_DEST.write_text(header + REFS_SRC.read_text())
    print(f"  synced {REFS_DEST.relative_to(REPO)}  <- icm-text/refs.bib")


def main() -> int:
    if not SOURCE.exists() or not any(SOURCE.iterdir()):
        sys.exit(
            f"icm-text/ not found or empty at {SOURCE}\n"
            "  run: git submodule update --init icm-text"
        )
    folders = sorted(
        p for p in SOURCE.iterdir() if p.is_dir() and CHAPTER_FOLDER_RE.match(p.name)
    )
    results: list[dict] = []
    for folder in folders:
        r = split_chapter(folder)
        if r:
            print(
                f"  ch{r['chapter_num']:02d}  {r['section_count']} section(s)  "
                f"<- icm-text/{r['slug']}"
            )
            results.append(r)
    if not results:
        sys.exit("no chapters found in icm-text/")
    regenerate_toc(results)
    print(f"  updated {TOC.relative_to(REPO)}")
    mirror_course()
    sync_references()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
