name: deploy-book

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy-book:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v4
        with:
          miniforge-version: latest
          environment-file: environment.yml
          activate-environment: icmbook
          auto-activate-base: false
          channels: conda-forge
          channel-priority: strict
          conda-remove-defaults: "true"

      - name: Build the book
        run: make book

      - name: Disable Jekyll processing
        run: touch _build/html/.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: _build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4